exclude = [ "__pycache__", "._*", ".AppleDouble", ".git", ".gitignore", ".ipynb_checkpoints", ".pylintrc", ".vscode", "*.exr", "*.pyc", "core", "*.egg-info", ".github",]
include = []
max_file_size = 100000
